################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../platform/emlib/src/em_cmu.c \
../platform/emlib/src/em_core.c \
../platform/emlib/src/em_cryotimer.c \
../platform/emlib/src/em_crypto.c \
../platform/emlib/src/em_emu.c \
../platform/emlib/src/em_gpio.c \
../platform/emlib/src/em_i2c.c \
../platform/emlib/src/em_msc.c \
../platform/emlib/src/em_rmu.c \
../platform/emlib/src/em_rtcc.c \
../platform/emlib/src/em_system.c \
../platform/emlib/src/em_usart.c 

OBJS += \
./platform/emlib/src/em_cmu.o \
./platform/emlib/src/em_core.o \
./platform/emlib/src/em_cryotimer.o \
./platform/emlib/src/em_crypto.o \
./platform/emlib/src/em_emu.o \
./platform/emlib/src/em_gpio.o \
./platform/emlib/src/em_i2c.o \
./platform/emlib/src/em_msc.o \
./platform/emlib/src/em_rmu.o \
./platform/emlib/src/em_rtcc.o \
./platform/emlib/src/em_system.o \
./platform/emlib/src/em_usart.o 

C_DEPS += \
./platform/emlib/src/em_cmu.d \
./platform/emlib/src/em_core.d \
./platform/emlib/src/em_cryotimer.d \
./platform/emlib/src/em_crypto.d \
./platform/emlib/src/em_emu.d \
./platform/emlib/src/em_gpio.d \
./platform/emlib/src/em_i2c.d \
./platform/emlib/src/em_msc.d \
./platform/emlib/src/em_rmu.d \
./platform/emlib/src/em_rtcc.d \
./platform/emlib/src/em_system.d \
./platform/emlib/src/em_usart.d 


# Each subdirectory must supply rules for building sources it contributes
platform/emlib/src/em_cmu.o: ../platform/emlib/src/em_cmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_cmu.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_core.o: ../platform/emlib/src/em_core.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_core.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_cryotimer.o: ../platform/emlib/src/em_cryotimer.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_cryotimer.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_crypto.o: ../platform/emlib/src/em_crypto.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_crypto.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_emu.o: ../platform/emlib/src/em_emu.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_emu.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_gpio.o: ../platform/emlib/src/em_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_gpio.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_i2c.o: ../platform/emlib/src/em_i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_i2c.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_msc.o: ../platform/emlib/src/em_msc.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_msc.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_rmu.o: ../platform/emlib/src/em_rmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_rmu.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_rtcc.o: ../platform/emlib/src/em_rtcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_rtcc.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_system.o: ../platform/emlib/src/em_system.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_system.d
	@echo 'Finished building: $<'
	@echo ' '

platform/emlib/src/em_usart.o: ../platform/emlib/src/em_usart.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -I"E:\Silabs\Propertise-Write No Response" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Include" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\src" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\drivers" -I"E:\Silabs\Propertise-Write No Response\platform\CMSIS\Include" -I"E:\Silabs\Propertise-Write No Response\iar" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\uartdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\src" -I"E:\Silabs\Propertise-Write No Response\platform\emlib\inc" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\soc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\common" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\common\inc" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\EFR32BG12_BRD4103A\config" -I"E:\Silabs\Propertise-Write No Response\platform\halconfig\inc\hal-config" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source" -I"E:\Silabs\Propertise-Write No Response\protocol\bluetooth\ble_stack\inc\common" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\halconfig" -I"E:\Silabs\Propertise-Write No Response\app\bluetooth\common\stack_bridge" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader\api" -I"E:\Silabs\Propertise-Write No Response\hardware\kit\common\bsp" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\gpiointerrupt\inc" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\sleep\inc" -I"E:\Silabs\Propertise-Write No Response\platform\radio\rail_lib\chip\efr32" -I"E:\Silabs\Propertise-Write No Response\platform\Device\SiliconLabs\EFR32BG12P\Source\IAR" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\src" -I"E:\Silabs\Propertise-Write No Response\platform\emdrv\tempdrv\inc" -I"E:\Silabs\Propertise-Write No Response\platform\bootloader" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DHAL_CONFIG=1' '-DEFR32BG12P332F1024GL125=1' --diag_suppress pa050 --diag_suppress pa050 --diag_error pe223 --diag_error pe223 --dependencies=m platform/emlib/src/em_usart.d
	@echo 'Finished building: $<'
	@echo ' '


